site_name: Liturgia Colors
site_url: https://unicolored.github.io/liturgia-colors/
repo_url: https://github.com/unicolored/liturgia-colors
site_description: A css theme inspired by liturgical colors in the Roman Church
site_author: unicolored
theme:
  name: material # Use mkdocs-material theme
  palette:
    primary: white # Customize colors
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Themes: themes.md
extra_css:
  - styles/liturgia.css
  - styles/liturgia.tailwind.css
  - styles/_themes.css
